Update wg_helper

diff --git a/wg_helper b/wg_helper
--- a/wg_helper
+++ b/wg_helper
@@ -4,7 +4,7 @@
 # URL: https://github.com/whiskerz007/wireguard_helper #
 ########################################################
 set_global_variables() {
-  CFG_DIR="/etc/wireguard"
+  CFG_DIR=${CFG_DIR:-/etc/wireguard}
   INTERFACE=${INTERFACE:-wg0}
   INTERFACE_PATH="${CFG_DIR}/${INTERFACE}.conf"
   INTERFACE_PORT=${INTERFACE_PORT:-51820}
@@ -37,19 +37,25 @@ set_global_variables() {
 # TODO: Verify addresses and endpoints are valid
 
 create_interface_config() {
+  if [ -f ${INTERFACE_PATH} ]; then
+    echo "Removing '${INTERFACE_PATH}'..."
+    rm ${INTERFACE_PATH}
+    unset INTERFACE_ENDPOINT
+    set_global_variables
+  fi
   if [ ! -f $INTERFACE_PRIVATEKEY_PATH ]; then
     echo "Generating $INTERFACE private key..."
     wg genkey | ( umask 007; cat > $INTERFACE_PRIVATEKEY_PATH; )
-	set_global_variables
   fi
   if [ -z "${INTERFACE_ENDPOINT}" ]; then
       local local_ip=$(hostname -I | cut -d ' ' -f1 ):${INTERFACE_PORT}
       printf "What is the interface endpoint? [${local_ip}] "
       read INTERFACE_ENDPOINT
     if [ -z "${INTERFACE_ENDPOINT}" ]; then
-	  INTERFACE_ENDPOINT=$local_ip
+      INTERFACE_ENDPOINT=$local_ip
     fi
   fi
+  set_global_variables
   echo "Generating config for $INTERFACE..."
   cat <<EOF > $INTERFACE_PATH
 # interface_endpoint: $INTERFACE_ENDPOINT
@@ -111,15 +117,15 @@ remove_peer() {
       return
     fi
     echo "Removing '${PEER}'..."
-	sed -i -e "${regex_remove}" $INTERFACE_PATH
+    sed -i -e "${regex_remove}" $INTERFACE_PATH
     rm ${PEER_PRIVATEKEY_PATH}
   elif [ $PEER_EXIST -eq 0 ]; then
     echo "ERROR: Unable to locate '${PEER}' in config."
-	echo "No changes have been made."
-	exit 1
+    echo "No changes have been made."
+    exit 1
   else
     echo "ERROR: Unknkown error while scanning for peer to remove."
-	exit 1
+    exit 1
   fi
 }
 
@@ -145,7 +151,7 @@ set_peer_state() {
   local regex_disable='/^# peer: '${PEER}'$/,/^$/ {/^$/b;/^#/!d;}'
   if [ $PEER_EXIST -eq 0 ]; then
     echo "ERROR: Peer does not exist"
-	exit 1
+    exit 1
   fi
   if [ true == $1 ]; then
     echo "Enabling peer ${peer}..."
@@ -163,13 +169,13 @@ EOF
 	
     [ ! -z $PEER_ENDPOINT ] && echo "Endpoint = ${PEER_ENDPOINT}" >> $INTERFACE_PATH
     [ ! -z $PEER_KEEPALIVE ] && echo "PersistentKeepalive = ${PEER_KEEPALIVE}" >> $INTERFACE_PATH
-	echo >> $INTERFACE_PATH
-	show_peer_conf
+    echo >> $INTERFACE_PATH
+    show_peer_conf
   elif [ false == $1 ]; then
     echo "Disabling peer ${peer}..."
     if [ $PEER_ENABLED -eq 0 ]; then
       echo "ERROR: Peer is already disabled."
-	  return 1
+      return 1
     fi
     sed -i -e "${regex_disable}" $INTERFACE_PATH
   else
@@ -193,7 +199,7 @@ next_ip() {
   if [ $result -eq 1 ]; then
     echo $next_address
   elif [ $result -eq 0 ]; then
-	echo $(echo $(($address_end + 1)) | sed -e "$(echo 's/^\(.*\)/'$(echo ${addresses[0]} | sed -e 's/\(.*\..*\..*\.\)[^\/]*/\1\\1\\/'))/")
+    echo $(echo $(($address_end + 1)) | sed -e "$(echo 's/^\(.*\)/'$(echo ${addresses[0]} | sed -e 's/\(.*\..*\..*\.\)[^\/]*/\1\\1\\/'))/")
   else
     echo "ERROR: Unknown problem scanning for next available IP address" >&2
     exit 1
@@ -204,7 +210,7 @@ cmd_clean() {
   local input
   echo "WARNING: About to delete Wireguard configs and all keys."
   echo ""
-  echo "ALL DATA IN ${CFG_DIR} WILL BE DELETED!"
+  echo "ALL DATA IN '${CFG_DIR}' WILL BE DELETED!"
   echo ""
   printf "Would you like to continue? [y/N] "
   read input
@@ -232,7 +238,7 @@ cmd_add() {
 cmd_remove() {
   if [ -z $PEER ]; then
     echo "ERROR: You must pass a peer to remove."
-	exit 1
+    exit 1
   fi
   remove_peer
 }
@@ -240,7 +246,7 @@ cmd_remove() {
 cmd_enable() {
   if [ -z $PEER ]; then
     echo "ERROR: You must pass a peer to enable."
-	exit 1
+    exit 1
   fi
   set_peer_state true
 }
@@ -248,7 +254,7 @@ cmd_enable() {
 cmd_disable() {
   if [ -z $PEER ]; then
     echo "ERROR: You must pass a peer to disable."
-	exit 1
+    exit 1
   fi
   set_peer_state false
 }
@@ -259,19 +265,19 @@ cmd_showconf() {
   fi
   case $CONF in
     interface)
-	  cat $INTERFACE_PATH
-	  ;;
-	peer)
+      cat $INTERFACE_PATH
+      ;;
+    peer)
       if [ -z $PEER ]; then
         echo "ERROR: You must pass a peer to show the configuration."
         exit 1
       fi
-	  show_peer_conf
-	  ;;
-	*)
-	  echo "ERROR: Invalid type passed. You must specify either 'interface' or 'peer'."
-	  exit 1
-	  ;;
+      show_peer_conf
+      ;;
+    *)
+      echo "ERROR: Invalid type passed. You must specify either 'interface' or 'peer'."
+      exit 1
+      ;;
   esac
 }
 
@@ -280,12 +286,12 @@ check_dependency() {
   local result
   for i in ${depends[@]}; do
     which $i 1> /dev/null
-	result=$?
-	if [ $result -eq 1 ]; then
-	  echo "ERROR: Missing one of the following dependencies."
-	  echo ${depends[*]}
-	  exit
-	fi
+    result=$?
+    if [ $result -eq 1 ]; then
+      echo "ERROR: Missing one of the following dependencies."
+      echo ${depends[*]}
+      exit
+    fi
   done
 }
 
@@ -329,6 +335,14 @@ process_parameters() {
           PEER_ALLOWED_IPS=$2
           shift; shift
           ;;
+        --cfg-dir)
+          CFG_DIR=$2
+          if [ ! -d $CFG_DIR ]; then
+            echo "ERROR: Directory '${CFG_DIR}' does not exist"
+            exit 1
+          fi
+          shift; shift
+          ;;
         *)
           echo "ERROR: Invalid parameters."
           usage
@@ -351,7 +365,7 @@ process_command() {
     *)
       echo "ERROR: Invalid command"
       usage
-	  exit 1
+      exit 1
       ;;
   esac
 }
@@ -362,31 +376,31 @@ usage() {
 USAGE: $(basename $0) COMMAND [OPTIONS]
        $(basename $0) showconf [interface|peer] [OPTIONS]
     COMMAND
-	init	Creates/overwrites wireguard config. Existing private key will be 
-		used during creation.
-	init-quick	Same as init but will prompt for first peer.
-	clean	Delete Wireguard configs and keys including peer keys located in 
-		${CFG_DIR}.
-	add	Add peer to a Wireguard interface.
-	remove	Remove peer from Wireguard interface. Config and keys will be removed.
-		This cannot be undone.
-	enable	Enable peer access.
-	disable	Disable peer access.
-	showconf	Show configuration for interface or peer.
+	init		Creates/overwrites wireguard config. Existing private key will be 
+			used during creation.
+	init-quick	Same as init and will additionally prompt for first peer.
+	clean		Delete Wireguard configs and keys including peer keys from config 
+			directory.
+	add		Add peer to a Wireguard interface.
+	remove		Remove peer configuration from Wireguard interface and delete keys.
+	enable		Enable peer access.
+	disable		Disable peer access.
+	showconf	Show configuration for interface or peer. (Default interface)
 
     OPTIONS
+	--cfg-dir	Location of configs and keys. (Default /etc/wireguard)
 	-p|--peer	Peer name.
         -i|--interface	Wireguard interface name. (Default wg0)
         --interface-endpoint|--peer-endpoint
-			Endpoint written as FQDN or IP followed by port seperated 
-			by a colon.
+			Endpoint written as FQDN or IP followed by port seperated by a colon.
+			(Example 'wireguard.com:51820, 1.2.3.4:51820')
 	--interface-address|--peer-address
 			Wireguard IP address for VPN connection.
 	--peer-keepalive|--peer-client-keepalive
 			Persistent keepalive
         -a|--allowed-ips
 			Comma seperate list of allowed ips written in CIDR notation.
-			(Example 0.0.0.0/0)
+			(Example '0.0.0.0/0')
 
 
 EOF
